spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/queuepay?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: possible_5344

  jpa:
    hibernate:
      ddl-auto: create
      generate-ddl: true
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: 3692807a737288
    password:  e43f90434b5687

    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true
            required: true



server:
  port: 8082
logging:
  level:
    org:
      springframework: WARN
      hibernate: WARN
    com:
      springsecurity:
        demo: DEBUG









## Server Connection
#server:
#  port: 8080
#  servlet:
#    context-path: /api/v1
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/QueuePay?createDatabaseIfNotExist=true&userSSL=false&serverTimezone=UTC
#    username: root
#    password: possible_5344
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect:  org.hibernate.dialect.MySQL5Dialect
