# Server Connection
server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/QueuePay?createDatabaseIfNotExist=true&userSSL=false&serverTimezone=UTC
    username: hadeoh
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.MySQL5Dialect
